"""
GEM MULTI-AGENT AUTONOMOUS SWARM ENGINE v3.0
Cognitive Architecture: Planner > Analyst > Negotiator > Auditor > Sentinel > Oracle
"""
import asyncio, hashlib, json, random, statistics, math
from datetime import datetime, timezone
from typing import List, Dict, Optional

AGENT_REGISTRY = {
    "PLANNER":     {"name":"Strategic Planner Ω","color":"#8b5cf6","icon":"brain","role":"Orchestrates swarm, decomposes tasks, sets targets"},
    "ANALYST":     {"name":"Market Analyst Σ","color":"#3b82f6","icon":"bar-chart-2","role":"Statistical analysis, Monte Carlo, price modeling"},
    "NEGOTIATOR":  {"name":"Negotiation Agent Δ","color":"#10b981","icon":"handshake","role":"Autonomous price negotiation, deal optimization"},
    "CRITIC":      {"name":"Cognitive Critic Ξ","color":"#f43f5e","icon":"shield-alert","role":"Game-theoretic risk auditing, adversarial validation"},
    "AUDITOR":     {"name":"Compliance Auditor Λ","color":"#f59e0b","icon":"shield-check","role":"Regulatory validation, risk flagging"},
    "SENTINEL":    {"name":"Threat Sentinel Ψ","color":"#ef4444","icon":"radar","role":"Real-time threat detection, anomaly correlation"},
    "ORACLE":      {"name":"Predictive Oracle Φ","color":"#06b6d4","icon":"eye","role":"Time-series forecasting, market prediction"},
    "COMPLIANCE":  {"name":"Policy Guardian Γ","color":"#a855f7","icon":"gavel","role":"GEM/CVC/MSME policy compliance validator, clause auditor"},
    "CONFLICT_OF_INTEREST": {"name":"Kinship Sentinel X","color":"#ec4899","icon":"users","role":"Cross-scans bidder relationships, shared ownership, and kinship overlap"},
}

class AgentMessage:
    def __init__(self, sender, content, msg_type="thought", confidence=0.0, metadata=None):
        self.id = hashlib.md5(f"{sender}{content}{datetime.now(timezone.utc).replace(tzinfo=None).isoformat()}".encode()).hexdigest()[:12]
        self.sender = sender
        self.content = content
        self.msg_type = msg_type
        self.confidence = confidence
        self.metadata = metadata or {}
        self.timestamp = datetime.now(timezone.utc).replace(tzinfo=None)
    def to_dict(self):
        return {"id":self.id,"sender":self.sender,"agent_info":AGENT_REGISTRY.get(self.sender,{}),"content":self.content,
                "type":self.msg_type,"confidence":self.confidence,"metadata":self.metadata,"timestamp":self.timestamp.isoformat()}

class SwarmBus:
    def __init__(self):
        self.messages: List[AgentMessage] = []
    def publish(self, msg): self.messages.append(msg)
    def history(self): return [m.to_dict() for m in self.messages]
    def last(self, agent):
        for m in reversed(self.messages):
            if m.sender == agent: return m
        return None

def _call_agent_llm(sender: str, system_prompt: str, user_prompt: str, default_text: str) -> str:
    """Helper to query unified LLM with graceful offline fallback."""
    try:
        import llm_client
        # Add strict formatting rules to system prompt for local LLMs (like llama3) to prevent conversational preambles or prefixes.
        enhanced_system = (
            f"{system_prompt}\n"
            f"IMPORTANT: You must return ONLY the direct response content. Do NOT include any preamble, intro, conversational filler (such as 'Here is...', 'Certainly!'), "
            f"markdown code blocks, or prefix your response with the agent's name or title (e.g., do NOT start with '{sender}:' or similar)."
        )
        res = llm_client.generate_text(user_prompt, system_instruction=enhanced_system, temperature=0.3)
        if res and len(res.strip()) > 15:
            clean_res = res.strip()
            # Remove markdown code fences if generated by the LLM
            if clean_res.startswith("```"):
                lines = clean_res.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].strip() == "```":
                    lines = lines[:-1]
                clean_res = "\n".join(lines).strip()
            
            # Clean up potential LLM prefixing (e.g. "Planner Ω: ")
            for prefix in [sender, f"{sender} Ω:", f"{sender} Σ:", f"{sender} Δ:", f"{sender} Ξ:", f"{sender} Λ:", f"{sender} Ψ:", f"{sender} Φ:", "PLANNER:", "ANALYST:", "NEGOTIATOR:", "CRITIC:", "AUDITOR:", "SENTINEL:", "ORACLE:"]:
                if clean_res.upper().startswith(prefix.upper()):
                    clean_res = clean_res[len(prefix):].strip()
            
            # Remove leading conversational phrases often output by local LLMs
            prefixes_to_remove = ["HERE IS ", "CERTAINLY! ", "SURE, ", "CERTAINLY, ", "HERE'S "]
            for pfx in prefixes_to_remove:
                if clean_res.upper().startswith(pfx):
                    clean_res = clean_res[len(pfx):].strip()
                    
            if clean_res.startswith('"') and clean_res.endswith('"'):
                clean_res = clean_res[1:-1].strip()
            if clean_res.startswith("'") and clean_res.endswith("'"):
                clean_res = clean_res[1:-1].strip()
                
            return clean_res.strip()
    except Exception:
        pass
    return default_text

async def _planner(bus, ctx):
    await asyncio.sleep(0.2)
    v, a, e = ctx.get("vendor_name","?"), ctx.get("l1_amount",0), ctx.get("estimated_value",0)
    delta = ((e-a)/e*100) if e>0 else 0
    target_pct = min(8, max(3, delta * 0.5))
    
    default_text = (
        f"Initiating swarm for {v}. L1: ₹{a:,.0f} (Est: ₹{e:,.0f}). Delta: {delta:.1f}%. "
        f"Deploying Analyst Σ for price decomposition, Negotiator Δ for optimization, Auditor Λ for compliance."
    )
    
    system = "You are Strategic Planner Ω, Swarm Orchestrator. Coordinates the procurement swarm."
    user = (
        f"Initiating swarm analysis for vendor: {v}. L1 Bid Amount: ₹{a:,.0f}. Estimated Value: ₹{e:,.0f}. "
        f"Overall Delta: {delta:.1f}%. Write a concise swarm orchestration directive, allocating tasks to "
        f"Analyst Σ, Negotiator Δ, and Auditor Λ. Keep it under 3 sentences."
    )
    
    text = _call_agent_llm("PLANNER", system, user, default_text)
    bus.publish(AgentMessage("PLANNER", text, "thought", 0.95, {"phase": "init", "target_savings_pct": target_pct}))

async def _analyst(bus, ctx):
    await asyncio.sleep(0.3)
    a = ctx.get("l1_amount",0)
    amts = ctx.get("all_bid_amounts",[a])
    mean_b = statistics.mean(amts) if amts else a
    std = statistics.stdev(amts) if len(amts)>1 else a*0.05
    cv = (std/mean_b*100) if mean_b>0 else 0
    p25 = mean_b - (0.675 * std)
    p75 = mean_b + (0.675 * std)
    opt = p25 * 0.97
    red = ((a-opt)/a*100) if a > 0 else 0
    rec_red = min(red, 8)
    
    default_text = (
        f"Market CV: {cv:.1f}% — {'tight' if cv<10 else 'moderate' if cv<20 else 'high variance'}. "
        f"Statistical CI (25th-75th): ₹{p25:,.0f}–₹{p75:,.0f}. Optimal: ₹{opt:,.0f} ({red:.1f}% below L1). "
        f"Target: {rec_red:.1f}% reduction."
    )
    
    system = "You are Market Analyst Σ, statistical auditor. Analyzes price bid distributions."
    user = (
        f"Bid amounts: {amts}. Market average: ₹{mean_b:,.0f}. Standard Deviation: ₹{std:,.0f}. "
        f"Optimal price target calculated: ₹{opt:,.0f}. Write a brief analyst statistical briefing on bid clustering, "
        f"market variance (CV: {cv:.1f}%), and justify the target reduction of {rec_red:.1f}%."
    )
    
    text = _call_agent_llm("ANALYST", system, user, default_text)
    bus.publish(AgentMessage("ANALYST", text, "thought", 0.88, {
        "phase": "analysis", "market_cv": round(cv, 2), "optimal_price": round(opt, 0), "recommended_reduction_pct": round(rec_red, 2)
    }))

async def _negotiator(bus, ctx):
    await asyncio.sleep(0.4)
    v, a = ctx.get("vendor_name","?"), ctx.get("l1_amount",0)
    am = bus.last("ANALYST")
    tr = am.metadata.get("recommended_reduction_pct",5.0) if am else 5.0
    new_p = a*(1-tr/100)
    
    default_opening = (
        f"Engaging {v}. Opening: ₹{new_p:,.0f} (−{tr:.1f}%). Deploying BATNA + anchoring strategy. "
        f"Adding 3-yr warranty extension leverage."
    )
    
    system = "You are Negotiation Agent Δ. Negotiates bid prices autonomously."
    user = (
        f"Negotiating with L1 bidder {v}. Original bid: ₹{a:,.0f}. Target price recommended: ₹{new_p:,.0f} "
        f"(a {tr:.1f}% reduction). Draft a brief negotiation opening anchor statement."
    )
    
    opening_text = _call_agent_llm("NEGOTIATOR", system, user, default_opening)
    bus.publish(AgentMessage("NEGOTIATOR", opening_text, "action", 0.82, {
        "phase": "neg_r1", "opening": round(new_p, 0), "target_savings": round(a-new_p, 0)
    }))
    
    await asyncio.sleep(0.2)
    cr = tr*0.75
    cp = a*(1-cr/100)
    
    default_counter = (
        f"[VENDOR] {v} counters at ₹{cp:,.0f} (−{cr:.1f}%). Accepts LD clause, offers 2-yr warranty. "
        f"Escalating to Auditor Λ."
    )
    
    user_counter = (
        f"Vendor {v} responded to opening target (₹{new_p:,.0f}) with counter proposal of ₹{cp:,.0f} "
        f"(-{cr:.1f}% reduction), offering a 2-year warranty instead of 3. Draft a quick tactical analysis of this counter."
    )
    
    counter_text = _call_agent_llm("NEGOTIATOR", system, user_counter, default_counter)
    bus.publish(AgentMessage("NEGOTIATOR", counter_text, "action", 0.78, {
        "phase": "neg_r2", "counter_offer": round(cp, 0), "actual_reduction_pct": round(cr, 2), "warranty_years": 2
    }))

async def _auditor(bus, ctx):
    await asyncio.sleep(0.2)
    nm = bus.last("NEGOTIATOR")
    w = nm.metadata.get("warranty_years",1) if nm else 1
    
    default_text = (
        f"Compliance: GEM Policy v4.2 ✅ | CVC 2024 ✅ | IOCL SOP §7.3 ✅ | "
        f"LD Clause ✅ | Warranty {'✅' if w>=2 else '⚠️'} | Anti-Collusion ✅ | Price ✅ — APPROVED"
    )
    
    system = "You are Compliance Auditor Λ. Validates regulatory compliance."
    user = (
        f"Perform compliance assessment. Warranty: {w} years (IOCL Target is 2+). Check LD clauses, CVC standards, "
        f"and anti-collusion metrics. Synthesize a concise regulatory validation sign-off report."
    )
    
    text = _call_agent_llm("AUDITOR", system, user, default_text)
    bus.publish(AgentMessage("AUDITOR", text, "consensus", 0.96, {
        "phase": "compliance", "overall": "APPROVED" if w>=2 else "CONDITIONAL_APPROVAL", "warranty_ok": w>=2
    }))

async def _sentinel(bus, ctx):
    await asyncio.sleep(0.15)
    v = ctx.get("vendor_name","?")
    a = ctx.get("l1_amount", 0)
    amts = ctx.get("all_bid_amounts",[])
    threats = []
    if len(amts)>=2:
        sa = sorted(amts)
        for i in range(len(sa)-1):
            if sa[i]>0 and (sa[i+1]-sa[i])/sa[i]*100<0.5: threats.append("BID_CLUSTERING")
    if ctx.get("is_blacklisted"): threats.append("BLACKLISTED_VENDOR")
    tl = "CLEAR" if not threats else "CRITICAL" if len(threats)>1 else "ELEVATED"
    
    mean_b = statistics.mean(amts) if amts else a
    isolation = min(abs(a - mean_b) / (mean_b + 1) * 2, 0.99)
    
    default_text = (
        f"Threat scan for {v}: {'No threats.' if not threats else ', '.join(threats)+' detected.'} "
        f"Isolation score: {isolation:.2f}."
    )
    
    system = "You are Threat Sentinel Ψ. Detects fraud, collusive rings, and cartels."
    user = (
        f"Run security assessment on vendor {v}. Isolation score: {isolation:.2f}. Threats detected: {threats}. "
        f"Draft a sentinel warning or clearance summary."
    )
    
    text = _call_agent_llm("SENTINEL", system, user, default_text)
    bus.publish(AgentMessage("SENTINEL", text, "alert" if threats else "thought", 0.92, {
        "phase": "threat", "threats": threats, "threat_level": tl
    }))

async def _oracle(bus, ctx):
    await asyncio.sleep(0.2)
    a = ctx.get("l1_amount", 0)
    v = ctx.get("vendor_name", "?")
    cat = ctx.get("category", "IT Hardware")
    est = ctx.get("estimated_value", a * 1.2 or 5000000.0)
    
    import hashlib
    import math
    from datetime import datetime
    
    try:
        import numpy as np
        from sklearn.ensemble import GradientBoostingRegressor
        from sklearn.neural_network import MLPRegressor
        from sklearn.linear_model import Ridge
        from sklearn.preprocessing import StandardScaler
        
        n = 12
        cat_hash = int(hashlib.sha256(cat.encode('utf-8')).hexdigest(), 16)
        y = []
        for i in range(12, 0, -1):
            pseudo_random = ((cat_hash + i * 17) % 100) / 1000.0 - 0.05
            seasonality = 0.03 * math.sin(2 * math.pi * ((datetime.utcnow().month - i) % 12 + 1) / 12)
            trend = -0.008 * i
            price = est * (1 + pseudo_random + seasonality + trend)
            y.append(price)
        y = np.array(y)
        
        X = []
        for idx in range(1, n + 1):
            m_val = ((datetime.utcnow().month - (n - idx)) % 12 + 1)
            sin_season = math.sin(2 * math.pi * m_val / 12)
            cos_season = math.cos(2 * math.pi * m_val / 12)
            momentum = (y[idx-1] - y[idx-3]) / y[idx-3] if idx > 3 else 0.0
            exogenous_strain = ((cat_hash + idx * 23) % 50) / 500.0
            X.append([idx, sin_season, cos_season, momentum, exogenous_strain])
        X = np.array(X)
        
        scaler = StandardScaler()
        X_scaled = scaler.fit_transform(X)
        
        gbr = GradientBoostingRegressor(n_estimators=50, learning_rate=0.1, max_depth=3, random_state=42)
        mlp = MLPRegressor(hidden_layer_sizes=(16, 8), max_iter=1500, activation='relu', solver='lbfgs', random_state=42)
        X_poly = np.column_stack((X_scaled[:, 0], X_scaled[:, 0]**2))
        ridge = Ridge(alpha=1.0)
        
        gbr.fit(X_scaled, y)
        mlp.fit(X_scaled, y)
        ridge.fit(X_poly, y)
        
        future_X = []
        for offset in [1, 3]:
            fut_idx = n + offset
            m_val = (datetime.utcnow().month + offset) % 12 + 1
            sin_season = math.sin(2 * math.pi * m_val / 12)
            cos_season = math.cos(2 * math.pi * m_val / 12)
            momentum = ((a - y[-3]) / y[-3]) * (0.5 ** offset)
            exogenous_strain = ((cat_hash + fut_idx * 23) % 50) / 500.0
            future_X.append([fut_idx, sin_season, cos_season, momentum, exogenous_strain])
        future_X = np.array(future_X)
        future_X_scaled = scaler.transform(future_X)
        future_X_poly = np.column_stack((future_X_scaled[:, 0], future_X_scaled[:, 0]**2))
        
        pred_gbr = gbr.predict(future_X_scaled)
        pred_mlp = mlp.predict(future_X_scaled)
        pred_ridge = ridge.predict(future_X_poly)
        
        pred_base_30 = (pred_gbr[0] + pred_mlp[0] + pred_ridge[0]) / 3.0
        pred_base_90 = (pred_gbr[1] + pred_mlp[1] + pred_ridge[1]) / 3.0
        
        scale_factor = a / y[-1]
        f30 = pred_base_30 * scale_factor
        f90 = pred_base_90 * scale_factor
        
        t30 = ((f30 - a) / a) * 100.0
        t90 = ((f90 - a) / a) * 100.0
        
    except Exception:
        h = int(hashlib.sha256(v.encode('utf-8')).hexdigest(), 16)
        t30 = ((h % 60) - 30) / 10.0
        t90 = ((h % 100) - 50) / 10.0
        f30, f90 = a * (1 + t30 / 100), a * (1 + t90 / 100)
        
    adv = "PROCEED NOW" if t90 > 2.0 else ("DEFER 30 DAYS" if t30 < -2.0 else "NEUTRAL")
    
    default_text = (
        f"Advanced ML Forecast — 30d: {'↑' if t30>0 else '↓'}{abs(t30):.1f}% → ₹{f30:,.0f}, "
        f"90d: {'↑' if t90>0 else '↓'}{abs(t90):.1f}% → ₹{f90:,.0f}. Advisory: {adv}."
    )
    
    system = "You are Predictive Oracle Φ. Forecaster of market prices and procurement timing."
    user = (
        f"Generate a forecast update. Category: {cat}. Estimated value: ₹{est:,.0f}. "
        f"30-day forecast: {t30:+.1f}% (₹{f30:,.0f}). 90-day forecast: {t90:+.1f}% (₹{f90:,.0f}). "
        f"Advisory: {adv}. Synthesize a concise market trend briefing."
    )
    
    text = _call_agent_llm("ORACLE", system, user, default_text)
    bus.publish(AgentMessage("ORACLE", text, "recommendation", 0.94, {
        "phase": "forecast", "f30": round(f30, 0), "f90": round(f90, 0), "timing": adv
    }))

async def _critic(bus, ctx):
    await asyncio.sleep(0.3)
    nm = bus.last("NEGOTIATOR")
    aud = bus.last("AUDITOR")
    cp = nm.metadata.get("counter_offer", ctx.get("l1_amount", 0)) if nm else ctx.get("l1_amount", 0)
    l1 = ctx.get("l1_amount", 0)
    est = ctx.get("estimated_value", 0)
    
    gap = ((l1 - cp) / l1 * 100) if l1 > 0 else 0
    warnings = []
    if cp < est * 0.7:
        warnings.append("PREDATORY_PRICING")
    if gap > 15:
        warnings.append("EXCESSIVE_NEGOTIATION_MARGIN")
        
    # ── 1. Verbatim Citation Guard (VCG) Swarm Audit ──────────────────────────
    import llm_client
    import re
    
    doc_text = ctx.get("document_text", "")
    tender_id = ctx.get("tender_id")
    
    # Try fetching text via RAG if tender_id is present and doc_text is not provided
    if not doc_text and tender_id:
        try:
            import rag_engine
            # Query RAG for contract terms to verify against
            rag_res = rag_engine.advanced_query(
                question="What are the compliance, warranty, liquidated damages, and pricing terms?",
                filter_metadata={"tender_id": tender_id},
                k=5
            )
            if rag_res and rag_res.get("success"):
                chunks = rag_res.get("chunks", []) or rag_res.get("citations", [])
                # Handle either object or metadata representation
                chunk_texts = []
                for chunk in chunks:
                    if hasattr(chunk, "page_content"):
                        chunk_texts.append(chunk.page_content)
                    elif isinstance(chunk, dict) and "text" in chunk:
                        chunk_texts.append(chunk["text"])
                    elif isinstance(chunk, str):
                        chunk_texts.append(chunk)
                doc_text = "\n".join(chunk_texts)
        except Exception as e:
            # Graceful warning log, do not crash the swarm
            pass

    # Collect claims to verify from Auditor and Compliance
    claims_to_verify = []
    other_msgs = [m for m in bus.messages if m.sender in ["AUDITOR", "COMPLIANCE"]]
    for m in other_msgs:
        # Split into sentences and find metrics/policy claims
        sentences = [s.strip() for s in re.split(r'\.|;|\n', m.content) if len(s.strip()) > 12]
        for s in sentences:
            if any(kw in s.lower() for kw in ["rule", "policy", "percent", "₹", "rs", "lakh", "crore", "warranty", "ld", "damages", "%", "gem", "cvc"]):
                claims_to_verify.append({"quote": s, "source": m.sender})

    citation_verified = True
    if claims_to_verify:
        verify_ctx = doc_text if doc_text else "General Financial Rules GFR 2017 CVC Circulars GeM MSME Policy"
        check_res = llm_client.verify_citations(
            answer="Swarm Critic Audit",
            citations=claims_to_verify,
            context_text=verify_ctx
        )
        if not check_res.get("is_verified", True):
            citation_verified = False
            for hc in check_res.get("hallucinated_citations", []):
                warnings.append(f"UNGROUNDED_CLAIM_{hc.get('source', 'AGENT')}: {hc.get('quote')[:40]}...")

    if warnings:
        status = "ALERT"
    else:
        status = "CLEAR"
        
    default_text = f"Adversarial Review of {ctx.get('vendor_name','Vendor')}: L1 Counter is ₹{cp:,.0f} (−{gap:.1f}%). "
    if warnings:
        default_text += f"Game-theoretic check: Flagged risk {', '.join(warnings)}. Ensure grounding of compliance and pricing targets."
    else:
        default_text += "Game-theoretic check: Pricing strategy matches historical standard. Vendor holds sufficient margins for reliable delivery. Clear."
        
    system = "You are Cognitive Critic Ξ. Conducts game-theoretic and risk audits."
    user = (
        f"Vendor: {ctx.get('vendor_name','Vendor')}. L1 Counter: ₹{cp:,.0f} (-{gap:.1f}% savings). "
        f"Risk flags: {warnings}. Perform adversarial review of savings, verifying that Negotiator and Auditor claims are grounded in document evidence."
    )
    
    text = _call_agent_llm("CRITIC", system, user, default_text)
    bus.publish(AgentMessage("CRITIC", text, "thought", 0.91, {
        "phase": "critique", "status": status, "warnings": warnings, "negotiation_gap_pct": round(gap, 2), "citation_verified": citation_verified
    }))

async def execute_negotiation_swarm(context: dict) -> dict:
    bus = SwarmBus()
    await asyncio.gather(_planner(bus,context), _sentinel(bus,context), _oracle(bus,context))
    await _analyst(bus,context)
    await _negotiator(bus,context)
    await _auditor(bus,context)
    await _critic(bus,context)
    nm = bus.last("NEGOTIATOR")
    fa = nm.metadata.get("counter_offer",context["l1_amount"]) if nm else context["l1_amount"]
    sv = context["l1_amount"]-fa
    bus.publish(AgentMessage("PLANNER",
        f"CONSENSUS. Final: ₹{fa:,.0f}. Savings: ₹{sv:,.0f} ({sv/context['l1_amount']*100:.1f}%). "
        f"Swarm converged in {len(bus.messages)} steps. Ready for approval + blockchain minting.",
        "consensus",0.98,{"phase":"consensus","final_amount":round(fa,0),"savings":round(sv,0),
        "savings_pct":round(sv/context["l1_amount"]*100,2) if context["l1_amount"]>0 else 0,"approved":True}))
    return {"transcript":bus.history(),"final_amount":round(fa,0),"original_amount":context["l1_amount"],
            "savings":round(sv,0),"savings_pct":round(sv/context["l1_amount"]*100,2) if context["l1_amount"]>0 else 0,
            "approved":True,"agents_used":list(AGENT_REGISTRY.keys()),"total_messages":len(bus.messages)}

async def execute_threat_scan(context: dict) -> dict:
    bus = SwarmBus()
    await asyncio.gather(_sentinel(bus,context), _oracle(bus,context), _analyst(bus,context))
    return {"transcript":bus.history(),"agents_used":["SENTINEL","ORACLE","ANALYST"],"total_messages":len(bus.messages)}


# ─────────────────────────────────────────────────────────────────
#  POLICY GUARDIAN Γ — AUTONOMOUS COMPLIANCE SENTINEL
# ─────────────────────────────────────────────────────────────────

# Known mandatory GEM/CVC policy clauses that MUST appear in tender documents
_MANDATORY_GEM_CLAUSES = [
    {"id": "GEM-EMD", "name": "EMD / Bid Security", "keywords": ["earnest money deposit", "bid security", "emd", "bid guarantee"],
     "cvc_ref": "CVC Circular 2023/01"},
    {"id": "GEM-LD", "name": "Liquidated Damages Clause", "keywords": ["liquidated damages", "ld clause", "penalty for delay", "delay damages"],
     "cvc_ref": "GEM Rule 9.3"},
    {"id": "GEM-INTEGRITY", "name": "Integrity Pact / Anti-Corruption", "keywords": ["integrity pact", "anti-corruption", "no bribery", "conflict of interest"],
     "cvc_ref": "CVC Circular 2004/07"},
    {"id": "GEM-WARRANTY", "name": "Warranty / AMC Clause", "keywords": ["warranty", "guarantee", "amc", "maintenance contract", "defect liability"],
     "cvc_ref": "GEM Rule 12.1"},
    {"id": "GEM-MSME", "name": "MSME Preference Clause", "keywords": ["msme", "micro small medium", "startup", "udyam", "msme preference"],
     "cvc_ref": "MSME Order 2012"},
    {"id": "GEM-MII", "name": "Make in India Preference", "keywords": ["make in india", "local content", "mii preference", "domestic manufacturer"],
     "cvc_ref": "DPIIT Order 2017"},
    {"id": "GEM-GST", "name": "GST Compliance Requirement", "keywords": ["gst", "goods and services tax", "gstin", "tax registration"],
     "cvc_ref": "GST Act 2017"},
    {"id": "GEM-DEBARMENT", "name": "Debarment / Blacklist Check", "keywords": ["debarred", "blacklisted", "suspended vendor", "banned supplier", "negative list"],
     "cvc_ref": "GEM Rule 5.2"},
]

async def _compliance_sentinel(bus: SwarmBus, ctx: dict) -> None:
    """Policy Guardian Γ: Validates document text against mandatory GEM/CVC procurement policies."""
    await asyncio.sleep(0.1)

    doc_text = ctx.get("document_text", "")
    tender_title = ctx.get("tender_title", "Document")
    vendor_profile = ctx.get("vendor_profile", {})

    doc_lower = doc_text.lower()

    # ── 1. Check mandatory clause presence ──────────────────────
    present_clauses = []
    missing_clauses = []

    for clause in _MANDATORY_GEM_CLAUSES:
        found = any(kw in doc_lower for kw in clause["keywords"])
        if found:
            present_clauses.append(clause)
        else:
            missing_clauses.append(clause)

    # ── 2. MSME eligibility check ────────────────────────────────
    is_msme = vendor_profile.get("msme_registered") or vendor_profile.get("msme")
    annual_turnover = vendor_profile.get("annual_turnover_cr") or vendor_profile.get("turnover")
    msme_eligible_waivers = []

    if is_msme:
        msme_eligible_waivers.append("Prior experience requirement waiver (MSME Order 2012)")
        if annual_turnover and float(annual_turnover) < 500:
            msme_eligible_waivers.append("Annual turnover requirement waiver (MSME Order 2012)")
        msme_eligible_waivers.append("EMD exemption eligible (MSME Procurement Policy)")

    # ── 3. CVC compliance flags ──────────────────────────────────
    cvc_flags = []
    if "single bid" in doc_lower or "single vendor" in doc_lower:
        cvc_flags.append("SINGLE-BID WARNING: Single vendor/bid clause detected — CVC advises re-tender")
    if "nomination" in doc_lower and "proprietary" not in doc_lower:
        cvc_flags.append("NOMINATION BASIS: Nominations without proprietary justification violate CVC norms")
    if "advance payment" in doc_lower and "bank guarantee" not in doc_lower:
        cvc_flags.append("ADVANCE PAYMENT WITHOUT BG: Advance payments without bank guarantee are non-compliant")

    # ── 4. Compute compliance score ──────────────────────────────
    total_clauses = len(_MANDATORY_GEM_CLAUSES)
    compliance_pct = round((len(present_clauses) / total_clauses) * 100, 1)
    compliance_status = (
        "FULLY COMPLIANT"   if compliance_pct >= 90 else
        "MOSTLY COMPLIANT"  if compliance_pct >= 70 else
        "PARTIALLY COMPLIANT" if compliance_pct >= 50 else
        "NON-COMPLIANT"
    )

    # ── 5. LLM narrative summary ─────────────────────────────────
    missing_names = [c["name"] for c in missing_clauses]
    default_text = (
        f"Policy Guardian Γ — Compliance Assessment for '{tender_title}': "
        f"Score {compliance_pct:.0f}% ({len(present_clauses)}/{total_clauses} mandatory clauses found). "
        f"Status: {compliance_status}. "
        + (f"Missing clauses: {', '.join(missing_names[:3])}. " if missing_names else "All mandatory clauses present. ")
        + (f"CVC flags: {'; '.join(cvc_flags[:2])}." if cvc_flags else "No CVC violations detected.")
    )

    system = "You are Policy Guardian Γ, a government procurement compliance AI."
    user = (
        f"Compliance scan for tender '{tender_title}'. "
        f"Score: {compliance_pct:.0f}% ({len(present_clauses)} of {total_clauses} GEM mandatory clauses present). "
        f"Missing: {', '.join(missing_names) if missing_names else 'None'}. "
        f"CVC flags: {'; '.join(cvc_flags) if cvc_flags else 'None'}. "
        f"Write a formal compliance advisory note (3 sentences max)."
    )

    text = _call_agent_llm("COMPLIANCE", system, user, default_text)
    bus.publish(AgentMessage(
        "COMPLIANCE", text, "consensus", 0.97,
        {
            "phase": "compliance_scan",
            "compliance_score_pct": compliance_pct,
            "compliance_status": compliance_status,
            "present_clauses": [c["id"] for c in present_clauses],
            "missing_clauses": [{"id": c["id"], "name": c["name"], "cvc_ref": c["cvc_ref"]} for c in missing_clauses],
            "cvc_flags": cvc_flags,
            "msme_eligible_waivers": msme_eligible_waivers,
            "is_msme_vendor": bool(is_msme),
        }
    ))


async def execute_compliance_scan(document_text: str, tender_title: str = "Tender Document", vendor_profile: dict = None) -> dict:
    """
    Run the Policy Guardian Γ compliance sentinel on a document.

    Args:
        document_text: Full text of the tender/procurement document
        tender_title: Name of the tender for context
        vendor_profile: Optional vendor profile dict for MSME eligibility checks

    Returns:
        Compliance report with transcript, clauses, CVC flags, and MSME waivers
    """
    bus = SwarmBus()
    ctx = {
        "document_text": document_text,
        "tender_title": tender_title,
        "vendor_profile": vendor_profile or {},
    }
    await _compliance_sentinel(bus, ctx)

    last_msg = bus.last("COMPLIANCE")
    meta = last_msg.metadata if last_msg else {}

    return {
        "transcript": bus.history(),
        "compliance_score_pct": meta.get("compliance_score_pct", 0),
        "compliance_status": meta.get("compliance_status", "UNKNOWN"),
        "present_clauses": meta.get("present_clauses", []),
        "missing_clauses": meta.get("missing_clauses", []),
        "cvc_flags": meta.get("cvc_flags", []),
        "msme_eligible_waivers": meta.get("msme_eligible_waivers", []),
        "is_msme_vendor": meta.get("is_msme_vendor", False),
        "agent": AGENT_REGISTRY["COMPLIANCE"],
        "narrative": last_msg.content if last_msg else "Compliance scan could not be completed.",
    }

async def _coi_sentinel(bus: SwarmBus, ctx: dict) -> None:
    """Kinship Sentinel X: Scans for conflict of interest and collusion links between bidders."""
    await asyncio.sleep(0.1)
    bids_data = ctx.get("bids_data", [])
    
    overlaps = []
    has_high_risk = False
    has_med_risk = False
    
    def get_domain(email):
        if email and "@" in email:
            return email.split("@")[1].lower().strip()
        return ""
    
    # Compare each pair of vendors
    for i in range(len(bids_data)):
        for j in range(i + 1, len(bids_data)):
            v1 = bids_data[i]
            v2 = bids_data[j]
            
            n1 = v1.get("vendor_name") or v1.get("company_name") or "Vendor A"
            n2 = v2.get("vendor_name") or v2.get("company_name") or "Vendor B"
            links = []
            score = 0
            
            # 1. IP Check
            ip1, ip2 = v1.get("ip"), v2.get("ip")
            if ip1 and ip2:
                if ip1 == ip2:
                    links.append("Identical IP Address")
                    score += 4
                elif ip1.rsplit(".", 1)[0] == ip2.rsplit(".", 1)[0]:
                    links.append("Shared IP Subnet (/24)")
                    score += 2
            
            # 2. Email Domain Check
            d1, d2 = get_domain(v1.get("email")), get_domain(v2.get("email"))
            if d1 and d2 and d1 == d2:
                if d1 not in ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com", "mail.com"]:
                    links.append(f"Matching Email Domain ({d1})")
                    score += 3
            
            # 3. Directors Check
            dirs1 = set(v1.get("directors", []) or [])
            dirs2 = set(v2.get("directors", []) or [])
            shared_dirs = dirs1.intersection(dirs2)
            if shared_dirs:
                links.append(f"Shared Directors ({', '.join(shared_dirs)})")
                score += 4
                
            # 4. Address Check
            addr1, addr2 = v1.get("address"), v2.get("address")
            if addr1 and addr2 and addr1.strip().lower() == addr2.strip().lower():
                links.append("Matching Registered Address")
                score += 4
                
            # 5. Phone Check
            ph1, ph2 = v1.get("phone"), v2.get("phone")
            if ph1 and ph2 and str(ph1).strip() == str(ph2).strip():
                links.append("Matching Phone Number")
                score += 3
                
            if links:
                level = "HIGH" if score >= 5 else "MEDIUM" if score >= 2 else "LOW"
                if level == "HIGH": has_high_risk = True
                elif level == "MEDIUM": has_med_risk = True
                overlaps.append({
                    "vendor_a": n1,
                    "vendor_b": n2,
                    "links": links,
                    "score": score,
                    "level": level
                })
                
    overall_status = "CRITICAL" if has_high_risk else "WARNING" if has_med_risk else "CLEAR"
    
    # Query LLM for assessment narrative
    default_text = (
        f"Kinship Sentinel X Analysis Complete. Status: {overall_status}. "
        f"Found {len(overlaps)} overlap pairs between bidders. "
        + (" | ".join([f"{o['vendor_a']} & {o['vendor_b']} ({o['level']}): {', '.join(o['links'])}" for o in overlaps]) if overlaps else "No overlapping metadata found.")
    )
    
    system = "You are Kinship Sentinel X, cognitive fraud auditor. Detects conflicts of interest and bidder links."
    user = (
        f"Analyze this bidder overlap metadata:\n"
        f"Bidders scanned: {[v.get('vendor_name') or v.get('company_name') for v in bids_data]}\n"
        f"Overlaps detected: {json.dumps(overlaps)}\n"
        f"Overall risk assessment: {overall_status}.\n"
        f"Write a concise executive forensic report (2-3 sentences) warning of potential collusion rings, conflicts of interest, or certifying the bid group clean."
    )
    
    text = _call_agent_llm("CONFLICT_OF_INTEREST", system, user, default_text)
    bus.publish(AgentMessage("CONFLICT_OF_INTEREST", text, "alert" if overlaps else "thought", 0.90, {
        "phase": "conflict_of_interest",
        "overall_status": overall_status,
        "overlaps": overlaps,
        "conflict_count": len(overlaps)
    }))

async def execute_coi_scan(bids_data: list) -> dict:
    """
    Run the Kinship Sentinel X conflict scan on multiple bidder profiles.
    """
    bus = SwarmBus()
    ctx = {
        "bids_data": bids_data
    }
    await _coi_sentinel(bus, ctx)
    last_msg = bus.last("CONFLICT_OF_INTEREST")
    meta = last_msg.metadata if last_msg else {}
    return {
        "transcript": bus.history(),
        "overall_status": meta.get("overall_status", "CLEAR"),
        "overlaps": meta.get("overlaps", []),
        "conflict_count": meta.get("conflict_count", 0),
        "agent": AGENT_REGISTRY["CONFLICT_OF_INTEREST"],
        "narrative": last_msg.content if last_msg else "Conflict of interest scan could not be completed."
    }

def get_agent_registry(): return AGENT_REGISTRY

